name: Java Release Build

on:
  push:
    tags:
      - 'v*'  # nur bei Tags wie v1.0.0, v0.1 usw.

permissions:
  contents: write  # notwendig für Release-Erstellung und Upload

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Repository klonen
        uses: actions/checkout@v3

      - name: Java installieren
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Maven Build
        run: mvn clean package

      - name: Release erstellen und .jar hochladen
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
