name: Build and Release

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install JavaFX
        run: sudo apt-get update && sudo apt-get install -y openjfx

      - name: Build with Ant
        run: ant -noinput -buildfile build.xml

  release:
    # Nur ausführen, wenn ein Tag gepusht wurde (z. B. v1.0.0)
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install JavaFX
        run: sudo apt-get update && sudo apt-get install -y openjfx

      - name: Build JAR
        run: ant -noinput jar

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: build/jar/FTF-Vokabeln.jar
